<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-N0G0NBDP" name="testNgScripts.HostelWorldTest" tests="4" failures="1" timestamp="06 Jun 2021 17:35:35 GMT" time="54.747" errors="0">
  <testcase name="setUpEmulator" time="35.801" classname="testNgScripts.HostelWorldTest"/>
  <testcase name="TestSearch" time="15.371" classname="testNgScripts.HostelWorldTest"/>
  <testcase name="destinationTest" time="3.341" classname="testNgScripts.HostelWorldTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	destination donot match expected [London] but found [London, England]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
destination donot match expected [London] but found [London, England]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testNgScripts.HostelWorldTest.destinationTest(HostelWorldTest.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- destinationTest -->
  <testcase name="SearchbuttonClick" time="0.234" classname="testNgScripts.HostelWorldTest"/>
</testsuite> <!-- testNgScripts.HostelWorldTest -->
